cmake_minimum_required(VERSION 3.27)
set(CMAKE_MESSAGE_LOG_LEVEL ERROR)
set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake" ${CMAKE_MODULE_PATH})
include(YosysVersion)

yosys_extract_version()
yosys_call_git(rev-parse --short=9 HEAD)
if(NOT "${git_result}" EQUAL "0")
	set(git_output "UNKNOWN")
endif()
set(yosys_version "${YOSYS_VERSION_MAJOR}.${YOSYS_VERSION_MINOR}+g${git_output}")
execute_process(COMMAND ${CMAKE_COMMAND} -E echo "${yosys_version}")
